[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "configparser>=7.2.0",
    "pytz>=2025.2",
    "slixmpp>=1.10.0",
]
